### ISSUE TITLE
Disable dynamic carousel?

### ISSUE THREAD

**Issue by anna-liao** [orianna-zzo/AllinOne#14]
Thanks, this is a great theme.

Is there a way to disable the dynamic image change on every page? I would like to change the background image manually by clicking on the arrows.

**Comment by anna-liao** [comment]
Or if there is only one image in `header-slides` to not show the dot or the arrows on the side.

**Comment by orianna-zzo** [comment]
Hi @anna-liao , thanks for loving it ^-^. 
You can change the property of Carousel (id="site-header") and set `data-interval="false"` in `homepage-header.html` and `post-header.html` to disable the automatically cycle. To remove the dot and the arrows, you can comment the `<!-- Indicators -->` section and `<!-- Controls -->` section.

**Comment by anna-liao** [comment]
Thanks!
